<?php
// $Id$

/*
 * hooks
 */
function uc_buyingclub_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#uc_buyingclub":
      $output = '<p>'. t("Views and forms for running a buying club with Ubercart"). '</p>';
      break;
  }
  return $output;
}

function uc_buyingclub_perm() {
  return array('access uc_buyingclub', 'create uc_buyingclub', 'administer uc_buyingclub');
}

function uc_buyingclub_menu() {
  $items = array();

  $items['buyingclub/finalize'] = array(
    'title' => "Buying Club: Finalize orders",
    'access arguments' => array('administer uc_buyingclub'),
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_buyingclub_finalization_form'),
  );

  $items['buyingclub/view/finalized'] = array(
    'title' => "Buying Club: View finalized orders",
    'access arguments' => array('administer uc_buyingclub'),
    'type' => MENU_CALLBACK,
    'page callback' => 'uc_buyingclub_view_finalized_orders',
  );

  $items['buyingclub/view/finalized/by_user'] = array(
    'title' => "Buying Club: View finalized orders by user",
    'access arguments' => array('administer uc_buyingclub'),
    'type' => MENU_CALLBACK,
    'page callback' => 'uc_buyingclub_view_finalized_orders_by_user',
  );

  $items['buyingclub/view/finalized/by_distributor'] = array(
    'title' => "Buying Club: View finalized orders by distributor",
    'access arguments' => array('administer uc_buyingclub'),
    'type' => MENU_CALLBACK,
    'page callback' => 'uc_buyingclub_view_finalized_orders_by_distributor',
  );

  $items['buyingclub/view/periods'] = array(
    'title' => "Buying Club: View ordering periods",
    'access arguments' => array('administer uc_buyingclub'),
    'type' => MENU_CALLBACK,
    'page callback' => 'uc_buyingclub_view_ordering_periods',
  );

  return $items;
}

function uc_buyingclub_block($op='list', $delta=0) {
  $block = array();

  if ($op == 'list') {
    $block[0]["info"] = t('Buying Club');
  }
  else if ($op == 'view') {
    $query = "SELECT nid, title FROM {node}";
    $query_result = db_query($query);
    $block_content = '';

    while ($links = db_fetch_object($query_result)) {
      $block_content .= l($links->title, 'node/'. $links->nid) .'</br>';
    }

    if ($block_content == '') {
      $block['subject'] = 'Buying Club';
      $block['content'] = 'No content';
    }
    else {
      $block['subject'] = 'Buying Club';
      $block['content'] = $block_content;
    }
  }
  return $block;
}

function uc_buyingclub_theme() {
  return array(
    'uc_buyingclub_finalization_form' => array(
      'arguments' => array('form', NULL)
    )
  );
}

function uc_buyingclub_mail($key, &$message, $params) {
  $language = $message['language'];
  $variables = user_mail_tokens($params['account'], $language);
  
  $store_values = uc_store_token_values('global');
  $buying_club_name = $store_values['store-name'];

  switch ($key) {
    case 'final_order':
      $message['headers'] = array(
        'MIME-Version' => '1.0',
        'Content-Type' => 'text/html',
      );
      $message['subject'] = t('Finalized '. $buying_club_name .' order', $variables, $language->language);

      $body = '<html><head></head><body>';
      $body .= t('Hello '. $buying_club_name .' member,<br /><br />', $variables, $language->language);
      $body .= t('Your order has been finalized:<br /><br />', $variables, $language->language);

      $body .= '<table cellpadding="3"><tr><th>Product</th><th>Quanity Desired</th><th>Quantity Ordered From Distributor</th></tr>';
      foreach ($params['products_given'] as $product => $given) {
        $body .= '<tr><td>'. $product .'</td><td>'. $params['products_desired'][$product] .'</td><td>'. $params['products_given'][$product] .'</td></tr>';
      }
      $body .= '</table>';

      $body .= '<br /><br />Your total cost will be ' . money_format('$%.2i', $params['total_cost']);
      $body .= '<br /><br />See you at the next pickup day,<br />'. $buying_club_name;
      $body .= '</body></html>';

      $message['body'] = $body;
      break;
  }
}


/*
 * order finalization
 */

/*
 * Create the finalization table and form.
 */
function uc_buyingclub_finalization_form($rows) {
  $ordering_period = _uc_buyingclub_get_most_recent_ordering_period();
  $start = $ordering_period->start;
  $end = $ordering_period->end;

  // warn user if this ordering period has already been (perhaps partially) finalized or should not yet be finalized
  $already_finalized_query = "SELECT count(op.order_product_id) AS num ".
    "FROM {uc_orders} o, {uc_order_products} op, {uc_buyingclub_order_products} bop ".
    "WHERE op.order_id=o.order_id AND bop.order_product_id = op.order_product_id ".
      "AND o.created > %d AND o.created < %d ";
  $already_finalized_result = db_query($already_finalized_query, $start, $end);
  if ($already_finalized_result && db_fetch_object($already_finalized_result)->num > 0) {
    drupal_set_message('Someone has already finalized this ordering period. Please contact an admin if changes need to be made.', $type='error');
  }

  if (time() < $end) {
    $date_format = "ga \o\\n l\, M jS Y";
    drupal_set_message('This ordering period is not over yet. Please wait until '. format_date($end, $type='custom', $format=$date_format) .' to finalize it!', $type='error');
  }

  // make query
  $distributor_db_info = content_database_info(content_fields('field_distributor')); 
  $distributor_table = $distributor_db_info['table'];
  $distributor_column = $distributor_db_info['columns']['nid']['column'];

  $minimum_order_db_info = content_database_info(content_fields('field_minimum_order')); 
  $minimum_order_table = $minimum_order_db_info['table'];
  $minimum_order_column = $minimum_order_db_info['columns']['value']['column'];

  $query = "SELECT p.title AS product_name, p.nid AS product_id, SUM(op.qty) AS order_product_qty, d.title AS distributor_name, ctd2.". $minimum_order_column ." AS minimum_order ".
    "FROM {uc_orders} o, {uc_order_products} op, {node} p, {node} d, {". $distributor_table ."} ctd, {". $minimum_order_table ."} ctd2 ".
    "WHERE p.type='product' AND d.type='distributor' AND op.order_id=o.order_id AND p.nid=op.nid ".
      "AND o.created > %d AND o.created < %d ".
      "AND ctd.vid=p.vid AND ctd.". $distributor_column ."=d.nid ".
      "AND ctd2.vid=p.vid ".
    "GROUP BY p.nid ".
    "ORDER BY d.title, p.title ";
  $query_result = db_query($query, $start, $end);

  // build table/form
  $form = array();

  if ($query_result) {
    while ($row = db_fetch_object($query_result)) {
      $form[$row->product_id]['product_id'] = array('#value' => stripslashes($row->product_id));
      $form[$row->product_id]['product_name'] = array('#value' => stripslashes($row->product_name));
      $form[$row->product_id]['order_product_qty'] = array('#value' => stripslashes($row->order_product_qty));
      $form[$row->product_id]['distributor_name'] = array('#value' => stripslashes($row->distributor_name));
      $form[$row->product_id]['minimum_order'] = array('#value' => stripslashes($row->minimum_order));
      $form[$row->product_id]['ordered_'. $row->product_id] = array(
        '#type' => 'textfield',
        '#default_value' => '0',
        '#maxlength' => 3,
        '#size' => 3,
        '#required' => FALSE,
      );
    }
  }

  $form['start'] = array(
    '#type' => 'hidden',
    '#value' => $start,
  );
  $form['end'] = array(
    '#type' => 'hidden',
    '#value' => $end,
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  $form['cancel'] = array(
    '#type' => 'markup',
    '#value' => l(t('Cancel'), 'dashboard'),
  );

  return $form;
}

/*
 * Theme finalization form as a table
 */
function theme_uc_buyingclub_finalization_form($form) {
  $rows = array();

  foreach (element_children($form) as $key) {
    if (isset($form[$key]['product_id'])) {
      $product_id = $form[$key]['product_id'];
      $row = array();
      $row[] = array('data' => drupal_render($form[$key]['product_name']));
      $row[] = array('data' => drupal_render($form[$key]['distributor_name']));
      $row[] = array('data' => drupal_render($form[$key]['order_product_qty']));
      $row[] = array('data' => drupal_render($form[$key]['minimum_order']));
      $row[] = array('data' => drupal_render($form[$key]['ordered_' . $key]), 'class' => 'textfield');
      $rows[] = $row;
      $form[$key]['#printed'] = TRUE;
      $form[$key]['product_id']['#printed'] = TRUE; // avoid re-rendering these
    }
  }

  $header = array();
  $header[] = t('Product');
  $header[] = t('Distributor');
  $header[] = t('Ordered by Members');
  $header[] = t('Minimum Order');
  $header[] = array('data' => t('Qty to Order'));

  // show which ordering period we're using
  $start = (int)$form['start']['#value'];
  $end = (int)$form['end']['#value'];
  $date_format = "ga l\, M jS Y";
  $output = 'Orders placed from '. format_date($start, $type='custom', $format=$date_format) .' to '. format_date($end, $type='custom', $format=$date_format);

  $output .= theme('table', $header, $rows);
  $output .= drupal_render($form);
  return $output;
}

/*
 * validate finalization form
 */
function uc_buyingclub_finalization_form_validate($form, &$form_state) {
  foreach ($form_state['values'] as $key => $value) {
    if (stripos($key, 'ordered_') === 0) {
      if ($value < 0) {
        form_set_error('', t('Negative orders are not allowed'));
      }
      if (!is_numeric($value)) {
        form_set_error('', t('Orders must be numbers'));
      }
    }
  }
}

/*
 * submit finalization form
 */
function uc_buyingclub_finalization_form_submit($form_id, $form) {
  $form_values = $form['values'];
  $prefix = 'ordered_';
  $start = $form_values['start'];
  $end = $form_values['end'];

  // finalize each product submitted with the quantity ordered as indicated
  foreach ($form_values as $key => $value) {
    if (stripos($key, $prefix) === 0) {
      $product_id = substr($key, strlen($prefix));
      $qty_ordered = $value;

      uc_buyingclub_finalize_product_order($product_id, $qty_ordered, $start, $end);
    }
  }

  // finalize each the total order for each user who ordered in this period
  uc_buyingclub_finalize_users($start, $end);

  drupal_get_messages(); // clear messages that were already displayed
  drupal_set_message(t('Ordered the given amounts for each product and notified purchasers'));
}

/*
 * Finalize all orders for a given product.
 *
 * @param $product_id
 *    The nid of the product node
 * @param $qty_ordered
 *    The quantity ordered through the finalization form
 * @param $start
 *    The start of the ordering period (in seconds)
 * @param $end
 *    The end of the ordering period (in seconds)
 */
function uc_buyingclub_finalize_product_order($product_id, $qty_ordered, $start, $end) {
  $query = "SELECT op.order_product_id AS id, op.qty AS qty_desired ".
    "FROM {uc_order_products} op, {uc_orders} o ".
    "WHERE op.order_id = o.order_id AND op.nid = %d ".
    "AND o.created > %d AND o.created < %d ".
    "ORDER BY o.created";

  $query_result = db_query($query, $product_id, $start, $end);

  $qty_available = $qty_ordered;
  if ($query_result) {
    while ($row = db_fetch_object($query_result)) {
      // determine how much of this order for this product will be fulfilled
      $qty_desired = $row->qty_desired;
      $qty_given = 0;

      if ($qty_available > 0) {
        if ($qty_desired <= $qty_available) {
          $qty_given = $qty_desired;
        }
        else { // give as much as we can
          $qty_given = $qty_available;
        }
      }

      // save
      $to_write = array(
        'order_product_id' => $row->id,
        'qty' => $qty_given,
        'finalized' => time(),
      );
      drupal_write_record('uc_buyingclub_order_products', $to_write);
      
      $qty_available -= $qty_given;
    }
  }
}

/*
 * Finalize orders for all users in the given ordering period.
 *
 * @param $start
 *    The start of the ordering period (in seconds)
 * @param $end
 *    The end of the ordering period (in seconds)
 */
function uc_buyingclub_finalize_users($start, $end) {
  $query = "SELECT DISTINCT o.uid AS user_id ".
    "FROM {uc_orders} o ".
    "WHERE o.created > %d AND o.created < %d";

  $query_result = db_query($query, $start, $end);

  if ($query_result) {
    while ($row = db_fetch_object($query_result)) {
      uc_buyingclub_finalize_user($row->user_id, $start, $end);
    }
  }
}

/*
 * Finalize orders for a given user in the given ordering period.
 *
 * @param $user_id
 *    The id of the user
 * @param $start
 *    The start of the ordering period (in seconds)
 * @param $end
 *    The end of the ordering period (in seconds)
 */
function uc_buyingclub_finalize_user($user_id, $start, $end) {
  $query = "SELECT op.title AS title, op.qty AS qty_desired, bop.qty AS qty_given, op.price AS price ".
    "FROM {uc_orders} o, {uc_order_products} op, {uc_buyingclub_order_products} bop ".
    "WHERE o.uid=%d AND o.created > %d AND o.created < %d ".
      "AND op.order_id = o.order_id AND bop.order_product_id = op.order_product_id";

  $query_result = db_query($query, $user_id, $start, $end);

  $total_cost = 0;
  $products_given = array();
  $products_desired = array();

  if ($query_result) {
    while ($row = db_fetch_object($query_result)) {
      // assemble summary, new price
      $price = (float)$row->price;
      $qty_given = (int)$row->qty_given;
      $qty_desired = (int)$row->qty_desired;

      $total_cost += ($price * $qty_given);

      if (!$products_given[$row->title]) $products_given[$row->title] = 0;
      $products_given[$row->title] += $qty_given;

      if (!$products_desired[$row->title]) $products_desired[$row->title] = 0;
      $products_desired[$row->title] += $qty_desired;
    }

    $account = user_load($user_id);
    $params = array(
      'name' => $account->name,
      'total_cost' => $total_cost,
      'products_given' => $products_given,
      'products_desired' => $products_desired,
    );

    $store_values = uc_store_token_values('global');
    drupal_mail('uc_buyingclub', 'final_order', $account->mail, user_preferred_language($account), $params, $store_values['store-email']);
  }
}

/*
 * view finalized orders (summary)
 */

function uc_buyingclub_view_finalized_orders() {
  // find start of most recent ordering period
  $period = _uc_buyingclub_get_most_recent_ordering_period();
  $start = $period->start;
  $end = $period->end;

  // query
  $distributor_db_info = content_database_info(content_fields('field_distributor')); 
  $distributor_table = $distributor_db_info['table'];
  $distributor_column = $distributor_db_info['columns']['nid']['column'];

  $minimum_order_db_info = content_database_info(content_fields('field_minimum_order')); 
  $minimum_order_table = $minimum_order_db_info['table'];
  $minimum_order_column = $minimum_order_db_info['columns']['value']['column'];

  $query = "SELECT p.title AS product_name, d.title AS distributor_name, SUM(op.qty) AS qty_desired, ctd2.". $minimum_order_column ." AS minimum_order, SUM(bop.qty) AS qty_ordered ".
    "FROM {uc_orders} o, {uc_order_products} op, {node} p, {node} d, {". $distributor_table ."} ctd, {". $minimum_order_table ."} ctd2, {uc_buyingclub_order_products} bop ".
    "WHERE p.type='product' AND p.nid=op.nid AND d.type='distributor' AND op.order_id=o.order_id AND bop.order_product_id = op.order_product_id ".
      "AND o.created > %d AND o.created < %d ".
      "AND ctd.vid=p.vid AND ctd.". $distributor_column ."=d.nid AND ctd2.vid=p.vid ".
    "GROUP BY p.nid ".
    "ORDER BY d.title, p.title ";

  $query_result = db_query($query, $start, $end);

  // make table
  $data = array();

  if ($query_result) {
    while ($row = db_fetch_array($query_result)) {
      $data[] = $row;
    }
  }

  // theme table
  return theme_table(array('Product', 'Distributor', 'Quantity Desired', 'Minimum Order', 'Quantity Ordered',), $data);
}

/*
 * view ordering periods
 */

function uc_buyingclub_view_ordering_periods() {
  // query
  $query = "SELECT p.start, p.end ".
    "FROM {uc_buyingclub_ordering_periods} p ".
    "WHERE 1 ".
    "ORDER BY p.start DESC ";

  $query_result = db_query($query);

  // make table
  $data = array();
  $date_format = "l\, M jS Y \a\\t ga";

  if ($query_result) {
    while ($row = db_fetch_array($query_result)) {
      $data[] = array(
        'start' => format_date((int)$row['start'], $type='custom', $format=$date_format),
        'end' => format_date((int)$row['end'], $type='custom', $format=$date_format),
      );
    }
  }

  // theme table
  return theme_table(array('Start', 'End'), $data);
}

/*
 * Show a summary by-user of the most recent ordering period. Meant to be something that could be printed and taken to a pickup day.
 */
function uc_buyingclub_view_finalized_orders_by_user() {
  drupal_add_css(drupal_get_path('module', 'uc_buyingclub') .'/uc_buyingclub.css');

  // find start of most recent ordering period
  $period = _uc_buyingclub_get_most_recent_ordering_period();
  $start = $period->start;
  $end = $period->end;

  // query
  $distributor_db_info = content_database_info(content_fields('field_distributor')); 
  $distributor_table = $distributor_db_info['table'];
  $distributor_column = $distributor_db_info['columns']['nid']['column'];

  $query = "SELECT o.billing_first_name AS member_first_name, o.billing_last_name AS member_last_name, p.title AS product_name, d.title AS distributor_name, SUM(op.qty) AS qty_desired, SUM(bop.qty) AS qty_ordered, op.price AS price ".
    "FROM {uc_orders} o, {uc_order_products} op, {node} p, {node} d, {". $distributor_table ."} ctd, {uc_buyingclub_order_products} bop ".
    "WHERE p.type='product' AND p.nid=op.nid AND d.type='distributor' AND op.order_id=o.order_id AND bop.order_product_id = op.order_product_id ".
      "AND o.created > %d AND o.created < %d ".
      "AND ctd.vid=p.vid AND ctd.". $distributor_column ."=d.nid ".
    "GROUP BY o.billing_last_name, o.billing_first_name, p.nid ".
    "ORDER BY o.billing_last_name, o.billing_first_name, d.title, p.title ";

  $query_result = db_query($query, $start, $end);

  // default output
  if (!$query_result || $query_result->num_rows === 0) {
    return "No orders to see for this period.";
  }

  // build output
  $date_format = "ga l\, M jS Y";
  $out = 'Orders placed from '. 
    format_date($start, $type='custom', $format=$date_format) .' to '. 
    format_date($end, $type='custom', $format=$date_format) .'<br /><br />';

  // start first table
  $current_member_name = '';
  $total_price = 0;
  $table = array();
  $table_headers = array('Product', 'Distributor', 'Quantity Desired', 'Quantity to Receive', 'Price',);

  while ($row = db_fetch_array($query_result)) {
    $member_name = $row['member_first_name'] .' '. $row['member_last_name'];
    if ($member_name !== $current_member_name) {
      // output old table
      if (count($table) > 0) {
        $table[] = array('', '', '', 'Total Due', money_format('$%.2i', $total_price));
        $out .= theme_table($table_headers, $table);
      }

      // start a new table
      $out .= '<div class="uc_buyingclub_member_name">'. $member_name .'</div>';
      $current_member_name = $member_name;
      $table = array();
      $total_price = 0;
    }

    // add this row to the table
    unset($row['member_first_name']);
    unset($row['member_last_name']);
    $price = (float)$row['price'] * (float)$row['qty_ordered'];
    $total_price += $price;
    $row['price'] = money_format('$%.2i', $price);
    $table[] = $row;
  }

  // output last table
  if (count($table) > 0) {
    $table[] = array('', '', '', 'Total Due', money_format('$%.2i', $total_price));
    $out .= theme_table($table_headers, $table);
  }

  return $out;
}

function uc_buyingclub_view_finalized_orders_by_distributor() {
  drupal_add_css(drupal_get_path('module', 'uc_buyingclub') .'/uc_buyingclub.css');

  // find start of most recent ordering period
  $period = _uc_buyingclub_get_most_recent_ordering_period();
  $start = $period->start;
  $end = $period->end;

  // query
  $distributor_db_info = content_database_info(content_fields('field_distributor')); 
  $distributor_table = $distributor_db_info['table'];
  $distributor_column = $distributor_db_info['columns']['nid']['column'];

  $query = "SELECT d.title AS distributor_name, p.title AS product_name, o.billing_first_name AS member_first_name, o.billing_last_name AS member_last_name, SUM(bop.qty) AS qty_ordered ".
    "FROM {uc_orders} o, {uc_order_products} op, {node} p, {node} d, {". $distributor_table ."} ctd, {uc_buyingclub_order_products} bop ".
    "WHERE p.type='product' AND p.nid=op.nid AND d.type='distributor' AND op.order_id=o.order_id AND bop.order_product_id = op.order_product_id ".
      "AND o.created > %d AND o.created < %d ".
      "AND ctd.vid=p.vid AND ctd.". $distributor_column ."=d.nid ".
      "AND bop.qty > 0 ".
    "GROUP BY d.title, p.nid, o.billing_last_name, o.billing_first_name ".
    "ORDER BY d.title, p.title, o.billing_last_name, o.billing_first_name ";

  $query_result = db_query($query, $start, $end);

  // default output
  if (!$query_result || $query_result->num_rows === 0) {
    return "No orders to see for this period.";
  }

  // build output
  $date_format = "ga l\, M jS Y";
  $out = 'Orders placed from '. 
    format_date($start, $type='custom', $format=$date_format) .' to '. 
    format_date($end, $type='custom', $format=$date_format) .'<br /><br />';

  $current_distributor_name = '';
  $current_product_name = '';
  $total_qty = 0;
  $table = array();
  $table_headers = array('Member', 'Quantity to Receive', );

  while ($row = db_fetch_array($query_result)) {
    if ($row['product_name'] !== $current_product_name) {
      // output old table
      if (count($table) > 0) {
        $table[] = array('Total quantity', $total_qty);
        $out .= theme_table($table_headers, $table);
      }

      // might also have a new distributor
      if ($row['distributor_name'] !== $current_distributor_name) {
        $out .= '<div class="uc_buyingclub_distributor_name">'. $row['distributor_name'] .'</div>';
        $current_distributor_name = $row['distributor_name'];
      }

      $out .= '<div class="uc_buyingclub_product_name">'. $row['product_name'] .'</div>';
      $current_product_name = $row['product_name'];
      $table = array();
      $total_qty = 0;
    }

    $total_qty += (int)$row['qty_ordered'];
    $table[] = array($row['member_first_name'] .' '. $row['member_last_name'], $row['qty_ordered']);
  }

  // output old table
  if (count($table) > 0) {
    $table[] = array('Total quantity', $total_qty);
    $out .= theme_table($table_headers, $table);
  }

  return $out;
}

/*
 * other useful functions
 */
function _uc_buyingclub_get_most_recent_ordering_period() {
  $query = "SELECT p.start, p.end ".
    "FROM {uc_buyingclub_ordering_periods} p ".
    "WHERE p.start < %d ".
    "ORDER BY p.start DESC ".
    "LIMIT 1";

  $query_result = db_query($query, time());

  if ($query_result) {
    $period = db_fetch_object($query_result);
  }

  return $period;
}
